name: flutter_js_platform_interface
description: A common platform interface for the flutter_js plugin.
homepage: https://github.com/dolphinxx/flutter_js/flutter_js_platform_interface

version: 0.4.0+5

dependencies:
  flutter:
    sdk: flutter
#  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"
