name: flutter_js_extension_boilerplate
description: Boilerplate for creating flutter js extension.
homepage: https://github.com/dolphinxx/flutter_js/flutter_js_extension_boilerplate

version: 0.4.0+5

dependencies:
  flutter:
    sdk: flutter
  #change to pub.dev package version or github path
  flutter_js_platform_interface:
    path: ../../flutter_js_platform_interface
  http: 0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  flutter_js:
    path: ../../flutter_js

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"
  